"""Pipeline constants, prompts, colors, fonts and policy data."""

from __future__ import annotations

import os
import re

from dotenv import load_dotenv

load_dotenv()
LLM_BASE_URL = os.getenv("LLM_BASE_URL", "").rstrip("/")
LLM_API_KEY = os.getenv("LLM_API_KEY", "")
LLM_MODEL = os.getenv("LLM_MODEL", "")
TTS_VOICE = os.getenv("TTS_VOICE", "hi-IN-SwaraNeural")
TTS_RATE = os.getenv("TTS_RATE", "-8%")
TTS_PITCH = os.getenv("TTS_PITCH", "+0Hz")
TTS_VOLUME = os.getenv("TTS_VOLUME", "+0%")
# Audio rule C3: loudness normalization of every TTS clip (off via TTS_LOUDNORM=off).
TTS_LOUDNORM = os.getenv("TTS_LOUDNORM", "on")
LOUDNESS_TARGET = float(os.getenv("LOUDNESS_TARGET", "-16.0"))  # LUFS, integrated
LOUDNESS_TP = float(os.getenv("LOUDNESS_TP", "-1.5"))  # dBTP true peak
LOUDNESS_LRA = 11.0  # LU, range gate
LOUDNESS_WPM = 135.0  # measured TTS speaking pace at -8% for the duration model
_SCHEMA_VERSION = 2
_REPEAT_POLICY_VERSION = 2
STUDIO_PROMPT = """You are an expert educator preparing a classroom lesson.
Read the documents below, then output a STRICT JSON lesson plan (no extra text).
Narration is written by a SEPARATE narration pass - leave every "narration"
field as an empty string "" and never spend output tokens on speech.

LESSON PLAN SCHEMA:
{{
  "title": "short lesson title",
  "opening": "1-2 sentence spoken intro (Roman-script Marathi-Hindi-English mix)",
  "scenes": [
    {{
      "section": "ONE section exactly (single value, not the list): 'What is this?', \
'Why do we need it?', 'How does it work?', 'Example', 'Takeaway'",
      "title": "short slide heading (ENGLISH); name the real source module/phase \
 here, e.g. '1: Data & testset (goldens)' - never put the module name in 'section'",
      "topic": "short canonical topic for this scene",
      "source_refs": ["source file or source heading reference"],
      "narration": "",

      "bullets": ["1-4 short ENGLISH bullet points for the slide"],
      "steps": ["numbered steps, 2-5 items (optional, empty array if none)"],
      "flow": ["arrow pipeline, e.g. A to B to C (optional, empty if none)"],
      "analogy": "one short real-life analogy in English (optional, empty if none)",
      "design_decision": "WHY this approach vs a REAL alternative the DOCUMENTS
                          imply, phrased 'X not Y because Z' (optional; empty
                          string if the docs don't distinguish an alternative)",
      "visual_diagram": "Optional. A diagram chain of REAL assets from the DOCUMENTS,
                         written as label nodes joined by '--- >' arrows, e.g.
                         '[Golden dataset] ---> [Judge] ---> [Verdict]'. Omit if none.",
      "code_snippet": "Optional. A real, VERBATIM command/JSON/assertion lifted from
                       the DOCUMENTS. Omit if none."
    }}
  ],
  "takeaways": ["3-5 short ENGLISH takeaway points"]
}}

RULES:
- exactly {scene_count} scenes (one per major source section / concept),
  matching a spoken length of about {target_minutes} minutes total
  (~130 words per minute). One scene per source concept; merge minor examples into
  their parent scene; never add a separate recap scene (takeaways are generated by the pipeline).
- NARRATION EMPTY (MANDATORY): every "narration" field MUST be "". A separate
  narration pass writes the spoken script from the finished plan - never write
  narration here, never budget output tokens for speech.
- OPENING LANG (MANDATORY): the "opening" field must be written ONLY in
  Latin/Roman script Marathi-Hindi-English mix (Hinglish). NEVER use Devanagari
  or any other script - Latin letters only, no matter the language. Do NOT write
  the opening entirely in English. Scatter a few everyday Marathi/Hindi words
  naturally (e.g. 'ha ka', 'samajh', 'accha', 'aaj', 'kya', 'kasa', 'mhanje').
  Technical words stay English. Example style (never copy this sentence;
  write your OWN opening about the LESSON TOPICS, not about embeddings):
  "Aaj aapne dekha ki yeast kaam kasa karto — chala step by step samajhuyacha."
- OUTPUT FORMAT (MANDATORY): reply with EXACTLY ONE ```json code block containing the
  WHOLE plan and nothing else. Never open a second ```json block anywhere. Never nest a
  JSON object or code fence inside an opening/bullet/analogy string - every
  string value is ONE quoted layer.
- OPENING SPOKEN (MANDATORY): the opening is a teacher's spoken line - NEVER slide
  metadata. Never say 'slide pe', 'yeh points likhe hain', 'exact points',
  'bullets', or read a bullet verbatim aloud. Write number prefixes out ('first',
  'step one' - never '1:' or '1.'), spell file names naturally ('module one',
  'active dot json', 'one over n plus one'), and NEVER leave raw symbols in the
  opening ('=', '&', '→', '/', backslashes, underscores, brackets are not spoken).
- Slide visible text (title, bullets, steps, flow, analogy, design_decision, visual_diagram,
  code_snippet, and takeaways) must stay in ENGLISH and use Latin script only; never emit Devanagari
  or any other non-Latin script in any slide-visible field.
- GROUNDING (MANDATORY): every slide fact and takeaway must be traceable to the DOCUMENTS.
  Never invent definitions, numbers, names, or examples not present in the docs. When the
  docs name concrete assets (module tables, lifecycle phases, pipeline stages, engine/option
  names, deferral registers), keep those names on the slide instead of generic restatements.
  Takeaways must reflect the docs' stated thesis and priorities, not generic advice.
- INTERVIEW FRAMING (MANDATORY): each scene's "design_decision" must explain a REAL
  design choice the DOCUMENTS make - e.g. 'gate lets a row through at
  tolerance-baseline, it is NOT a blocking guardrail'. Ground it in contrast language
  the docs actually use (unlike, never, must, not the same as, instead of, rather
  than) or two similar concepts defined near each other. If the docs don't support a
  genuine distinction, set "design_decision" to "" - never invent an interview
  question or a plausible alternative the docs don't mention.
- TAKEAWAYS (MANDATORY): takeaways are synthesized CONCLUSIONS/DECISIONS in
  DIFFERENT wording from the scene bullets - never restate a bullet verbatim.
- SOURCE-DRIVEN OUTLINE (MANDATORY): build the scene list from the DOCUMENTS' own
  structure - their headings, module/table rows, lifecycle phases, named components,
  and registers. Name scenes after real elements that appear in the docs. A scene
  title or bullet that would fit any topic's generic course template ("What is X?",
  "Improves accuracy", "Provides feedback", "Ensures quality") is REJECTABLE -
  replace it with the docs' actual content.
- SCENE COUNT (HARD): exactly {scene_count} scenes, never more, never fewer.
- UNIQUENESS: every bullet line must be unique across the whole lesson.
- WHITEBOARD VISUALS: "section" must be ONE of the five schema values above; the
   source element name goes in "title". "visual_diagram" must be a short chain of REAL
   component names from the DOCUMENTS joined by '--- >' arrows, and every label must
   illustrate THIS slide's OWN topic (the slide title) - never another concept's
   assets. For a tolerance/threshold concept, draw the comparison chain itself
   (e.g. '[Run Value] ---> [Delta vs Baseline] ---> [Absolute/Relative Threshold]'),
   not a baseline-pointer file. "code_snippet" must be
   a verbatim real command, path, JSON, or assertion from the DOCUMENTS (e.g. 'uv sync',
   'compare.py --baseline active.json') - never invented pseudo-code or made-up
   function names like 'compare function'.
- SOURCE-DRIVEN RICHNESS (HARD): every scene needs 2+ substantive bullets drawn from the
    DOCUMENTS for that concept. A single generic word ("Canonical pointer") is REJECTABLE -
    replace it with the doc's actual specifics (e.g. for `active.json`: the full schema
    `{{schema_version, baseline_id, path}}`, the resolve-BEFORE-compare rule, the atomic
    rewrite, and the path-safety checks). A title or bullet that fits any generic course
    template is REJECTABLE. For schema/state concepts (e.g. a config or pointer file),
    output the ACTUAL JSON keys, path rules, and structural fields inside the bullet text -
    never a paraphrase or placeholder.
- Never return text outside the JSON. No markdown fences around it.
- Output JSON only.

DOCUMENTS:
{content}"""
NARRATION_PROMPT = """You are the narration writer for an existing lesson plan.
Below are the finished scenes (section, title, bullets, steps, design_decision)
and a source excerpt. Write the SPOKEN script for EVERY scene in Roman-script
Marathi-Hindi-English (Hinglish) - the studio's teaching voice. The planner
left every "narration" blank; YOUR output becomes the whole spoken track.

Return EXACTLY ONE JSON ARRAY (no extra text, no markdown fences other than the
array), one object per scene IN ORDER:
[{"scene": 1, "narration": "..."}, {"scene": 2, "narration": "..."}, ...]

For EVERY scene's "narration" write 30-55 spoken words as 2-4 COMPLETE
sentences that TEACH that scene's ONE concept. Requirements:

- LANG (MANDATORY): Latin/Roman script ONLY - never Devanagari or any other
  script. NEVER write a narration entirely in English. Scatter a FEW everyday
  Marathi/Hindi words ('ha', 'samajh', 'accha', 'aaj', 'kya', 'mhanje'); use
  DIFFERENT ones per scene and never paste this word list.
- SPOKEN, NOT SLIDE METADATA: you are a teacher explaining - never 'slide pe',
  'yeh points likhe hain', 'exact points', or 'bullets'. Do NOT read bullets or
  the title verbatim, and never open a narration by re-reading the scene title
  (mention it at most once).
- NO RAW SYMBOLS: write number prefixes out ('first', 'step one' - never '1:'
  or '1.'), spell file names naturally ('module one', 'active dot json', 'one
  over n plus one'), and never leave '=', '&', '→', '/', backslashes,
  underscores or brackets in the narration.
- TEACH ONE CONCEPT: narrate the reasoning behind the scene - what it is, why
  this approach (lean on "design_decision") and not another, what happens on
  failure, what limit applies. Do not cram several concepts into one scene.
- GROUNDING: every fact must be traceable to the SOURCE EXCERPT - never invent
  definitions, numbers, names, or examples.
- VARY: every scene's narration must START and END differently; never reuse a
  closing phrase or any full sentence across scenes. No rhetorical fillers
  ('thik hai? na?') and no 'isliye aaj hum samajhe ge' non-closures.
- Keep each narration between 30 and 55 spoken words; the whole lesson should
  stay near {scene_count} times 40 words.

Return the JSON ARRAY only - no prose before or after it."""
TOPIC_PROMPT = """List the 1-3 CENTRAL topics covered by the documents below.
Return ONLY a JSON array of short topic strings, e.g. ["rag and retrieval", "observability"].
No extra text, no markdown fences.

DOCUMENTS:
{content}"""
_BANNED_EXAMPLE = re.search(r'Example style.*?"([^"]+)"', STUDIO_PROMPT,
                            re.DOTALL)
_BANNED_NGRAMS: set[tuple[str, ...]] = set()
_BANNED_DISTINCT: set[str] = set()
if _BANNED_EXAMPLE:
    _B_EX_TOKS = [w for w in re.findall(r"[a-z0-9]+", _BANNED_EXAMPLE.group(1).lower())]
    for _n in (2, 3):
        _BANNED_NGRAMS |= {tuple(_B_EX_TOKS[_i:_i + _n])
                           for _i in range(max(0, len(_B_EX_TOKS) - _n + 1))}
    _BANNED_DISTINCT = {t for t in _B_EX_TOKS if len(t) >= 7}
_MHE_MARKERS = {
    "accha", "aaj", "aap", "hai", "kaise", "kar", "karte", "kya", "kyun",
    "mhanje", "sakta", "samajh", "seekhe", "seekhenge", "sikha", "sirf",
    "sodya", "unka", "unke", "woh", "yeh",
}
_NARR_MIN_TOKENS = 12
_SECTIONS = ("what is this", "why do we need it", "how does it work", "example", "takeaway")
_ENUM_HINTS = (
    ("what is this", ("schema", "contract", "definition", "identifier",
                      "metadata", "registry", "defines")),
    ("why do we need it", ("why", "risk", "without it", "guardrail-like")),
    ("how does it work", ("compare", "gate", "pipeline", "process",
                          "mechanism", "mirror", "frozen", "baseline")),
    ("example", ("example", "sample", "walkthrough", "trace", "scenario")),
    ("takeaway", ("takeaway", "recap", "key point", "summary", "remember")),
)
_DD_GENERIC = (
    "must be consistent", "consistent across", "not out of scope",
    "because the docs", "as you can see", "simply because",
)
_DEVANAGARI = re.compile(r"[\u0900-\u097F]")
_TEMPLATE_AHEM = re.compile(
    r"(?:aage badhte hai\s+)?ek ahem module hai,?\s+hum yeh samajhenge ki "
    r"kya (?P<c>[^.]*)\.", re.I)
_TEMPLATE_SEEKHTE = re.compile(
    r"chaliye\s*['\"]*seekhte hai\s+kya (?P<c>[^.]*)\.\s*['\"]*", re.I)
_NARR_HEADS = ("Yahan samjho", "Ab dekho", "Ismein focus karo", "Main point",
               "To chaliye dekhein", "Aur yahan dekhte hain")
_DD_LEADS = ("Reason yahi hai ki ", "Iska ahem reason yeh hai ki ",
             "Design choice dekho, ", "Yeh is soch ke banaya, ",
             "Core decision yeh hai, ", "Asli wajah yeh hai, ",
             "Faisla yeh hua, ", "Isliye design aisa hai, ")
_POINTS_LEADS = (" Aur slide ke exact points: ", " Slide pe yeh points likhe hain: ",
                 " Aur in points pe dhyaan do: ", " Slide ke asli points: ",
                 " Aur points, ek ek karke: ", " Slide ke main points: ",
                 " Slide ke yeh key points hain: ", " Points abhi padhte hain: ")
_OPENER_POOL: list[str] = [
    "Is scene mein hum ek fresh concept samjhenge. ",
    "Ab chaliye isse detail mein dekhte hain. ",
    "Yahan hum ek important piece samjhte hain. ",
    "Ek key idea ka asaan explanation lete hain. ",
    "Is baar hum simple terms mein explore karenge. ",
    "Samajhne ke liye step-by-step chalein. ",
    "Isko ek hi example se clear kiya jaa sakta hai. ",
    "Chaliye ab iska kaam karne ka tareeka dekhte hain. ",
]
_CLOSER_POOL: list[str] = [
    " to yehi hai iska matlab.",
    " to yahan baat clear ho gayi.",
    " ye hi tha iska asli kaam.",
    " to isse agle scene mein use karenge.",
]
MIN_SCENES = 5
TARGET_MAX_SCENES = 8
AUTO_TRIM_MAX_SCENES = 12
_CONTRAST_RE = re.compile(
    r"\b(?:unlike|never|must(?!aybe)|not the same as|instead of|rather than|"
    r"as opposed to|compared with|whereas)\b",
    re.IGNORECASE,
)
BG = (18, 24, 38)
PANEL = (30, 40, 60)
ACCENT = (66, 133, 244)
GOLD = (255, 193, 7)
GREEN = (76, 175, 80)
FG = (235, 238, 245)
MUTED = (150, 158, 175)
TITLE_HOLD = 4.0  # seconds the cover card stays before the first scene
_VIDEO_BODY_MAX = 652  # int(H) - 68 for the 720px canvas
_SOFT_PREFIXES = ("narration pure-English",
                   "repeating narration phrase",
                   "near-duplicate bullets vs takeaways",
                   "placeholder title restates section",
                   "fused slide token")
PACKAGE_NAME = "doc-to-video-tutor"
PACKAGE_VERSION = "0.1.0"
BRAND_NAME = PACKAGE_NAME
BRAND_TAGLINE = "learn by listening"
BRAND_FOOTER = f"{BRAND_NAME} v{PACKAGE_VERSION} — {BRAND_TAGLINE}"
